name: CI

on:
  push:
    branches: [ Dev, main ]
  pull_request:
    branches: [ Dev, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Run tests
        env:
          NODE_ENV: test
          JWT_SECRET: test_secret_1234567890
        run: npm test --silent
